# Generated by Django 3.2.8 on 2021-10-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211029_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='link',
        ),
    ]
